name: build
 
on: 
  push:
    branches:
      - main
  
jobs:
  permissions:
    contents: write
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: cp  _site/assets/favicon.*  _site/assets/images/. # fix for  favicon
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  _site 
          publish_branch: gh-pages
        
         
